### PR TITLE
Removed the query for TotalResults when the query is non-windowed

### PR DESCRIPTION
**Pull request by chessydk**
Hi Asger - don't know if your'e interesting in this PR. I just noticed that for a non-windowed queries (no skip/take's) there was still a query sent to the server, to ask for the total rows, although it could be deducted from the rows returned. So 2 practically equal queries were sent off and only 1 necessary.

I do call ToList() on the returned rows when they get back to be able to call Count, but I don't think its a problem, as the rows has been fetched already. Also further call to ToList() on the returned IEnumerable would just do nothing...

All tests are green (didn't make any new ones).

### CODE REVIEW

**Comment by asgerhallas** [comment]
@chessydk it is now deployed as 0.9.6, sorry I forgot to do it sooner :)
Thank you for the fix!

**Comment by mookid8000** [comment]
👍

**Comment by chessydk** [comment]
Hi Asger - was going to update it in my projekt now, but I see there's a nuget ver. 0.10.0 as well (which is older than 0.9.6). But still fine to grab 0.9.6 ?

**Comment by asgerhallas** [comment]
Damn... that looks like I assumed natural ordering of git tags, when I checked what was the latest. Let me just fix it.

**Comment by chessydk** [comment]
Super, thx.

**Comment by asgerhallas** [comment]
Sorry about that. A version 0.10.1 has just been published.

**Comment by chessydk** [comment]
Thx. Hmm - there's something strange though. When I update it (Update-Package HybridDb) it installs as 1.0.0.0. And if I specify the version explicitly (Update-Package HybridDb -Version 0.10.1) it throws an error at me, saying it can't find it. Update! - now it works - some timing issue on nuget.org, maybe... THX.

**Pull request merged**
